services:
  database:
    image: mysql:8.2.0-oracle
    container_name: mysql
    environment:
      MYSQL_USER: ${user}
      MYSQL_ROOT_PASSWORD: ${root_password}
      MYSQL_PASSWORD: ${password}
      MYSQL_DATABASE: ${db}

    networks:
      - spring_lesson_3
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - database-volumes:/var/lib/mysql
    restart: unless-stopped

volumes:
  database-volumes:

networks:
  spring_lesson_3: